# Generated by Django 2.0.6 on 2018-06-30 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='AuthorDetial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('is_pub', models.BooleanField()),
                ('pub_date', models.DateField()),
                ('authors', models.ManyToManyField(to='App01.Author')),
            ],
        ),
        migrations.CreateModel(
            name='gander',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('tel', models.IntegerField(unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.Publish'),
        ),
        migrations.AddField(
            model_name='author',
            name='authorDetial',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App01.AuthorDetial'),
        ),
        migrations.AddField(
            model_name='author',
            name='sex',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App01.gander'),
        ),
    ]
