# Generated by Django 2.0.6 on 2018-06-30 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App01', '0003_auto_20180630_1403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App01.gander'),
        ),
    ]
